### ISSUE TITLE
Wikipedia update

### ISSUE THREAD

**Issue by toooonyy** [Krasjet/wikipedia.rehash#1]
Wikipedia(english) now has an updated table of contents section, will there be update for this usercss?

-------------

without usercss

<img width="1401" alt="Screen Shot 2023-02-01 at 15 47 18" src="https://user-images.githubusercontent.com/3480434/216075458-474b12e6-d757-4144-9508-6238672748e2.png">

-------------

enabled
<img width="1403" alt="Screen Shot 2023-02-01 at 15 47 31" src="https://user-images.githubusercontent.com/3480434/216076241-23905527-214f-4af8-a71e-fd80132e1403.png">

**Comment by Krasjet** [comment]
You can use the [`v2`](https://github.com/Krasjet/wikipedia.rehash/tree/v2) branch for the updated layout. I'll do a more careful design update later.
